### ISSUE TITLE
Regarding Project

### ISSUE THREAD

**Issue by prajwals420** [siddhiimhatre/Movie_Website#1]
On the home page of the project  only 2 videos are play able for Spiderman and Jumanji...right.? Apart from that if we click on any other movie. It will redirect us to the home page.?

**Comment by siddhiimhatre** [comment]
Yeah because I didn't uploaded all videos. actually I didn't have trailers
of all films at that time so I uploaded only two.

**Comment by prajwals420** [comment]
Thanks for the update. Btw great project.!
